name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies (light but compatible)
        run: |
          python -m pip install --upgrade pip wheel
          # If you have a requirements.txt, install it first.
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Test deps (quiet to keep logs clean)
          pip install -q pytest pytest-cov pytest-mock pillow imageio numpy pydicom nibabel
          pip install -q shap google-generativeai reportlab opencv-python-headless
          # Try to get CPU TF; if it fails, tests that require TF will be skipped
          pip install -q tensorflow-cpu==2.17.1 || echo "TensorFlow not available; TF tests will be skipped"

      - name: Run tests
        env:
          # Prevent Streamlit (if imported) from trying to open a browser
          STREAMLIT_HEADLESS: "1"
        run: |
          pytest -q --maxfail=1 --disable-warnings --cov=src --cov-report=term-missing

      # Optional: uncomment when ready
      # - name: Lint (Ruff) & Format check (Black)
      #   run: |
      #     pip install -q ruff black
      #     ruff check .
      #     black --check .
